### ISSUE TITLE
Wemo miniPlug

### ISSUE THREAD

**Issue by philkruger57** [jason0x43/hubitat#8]
When another controller (Alexa) Switches on/off the mini, Hubitat does not see the change.
I also have Caseta  and when Alexa Switches it on/off I can see the effect in Hubitat. What am I missing?

**Comment by jason0x43** [comment]
Sorry for the delayed response. That generally means that Hubitat has lost its subscription to the device. Try opening the device in Hubitat and clicking "Subscribe", then see if it reacts as expected.

**Comment by philkruger57** [comment]
Thanks for responding. Mute point now as I've decided to abandon Wemo
(cloud) in favor of Sengled Plug Smart Outlet. (No cloud) Our internet
here, SuddenLink, is not 100% reliable

**Comment by jason0x43** [comment]
WeMo devices don't actually require cloud access to work; both the WeMo phone app and the driver in this repo work locally (the driver _only_ works locally). Well, at least the older devices don't. I only ever bought a couple of WeMo devices (an original motion sensor and switch). 😄

I'll close this since it sounds like it's no longer relevant.
